[nitpick.files.absent]
"pytest.ini" = "use pyproject.toml instead"

#
# flake8 config
#
[".flake8".flake8]
exclude = ".git,__pycache__,docs/source/conf.py,.venv,old,build,dist,.aws-sam"
max-line-length = 120
max-complexity = 20
doctests = true

# ignore errors
# W503: line break before binary operator
# D100: Missing docstring in public module
# D104: Missing docstring in public package
# D400: First line should end with a period
# D415: First line should end with a period, question mark, or exclamation point
# NIP*: (flake8-nitpick plugin check results.) It checks *.py(like setup.py) in the root dir but there's nothing.
ignore = "W503,D100,D104,D400,D415,NIP"
# docstrings convention
convention = "google"

#
# black config
#
["pyproject.toml".tool.black]
line-length = 120

#
# isort config
#
# https://github.com/andreoliwa/nitpick/blob/develop/src/nitpick/resources/python/isort.toml
["pyproject.toml".tool.isort]
line_length = 120

# The configuration below is needed for compatibility with black.
# https://github.com/python/black#how-black-wraps-lines
# https://github.com/PyCQA/isort#multi-line-output-modes
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true

#
# mypy config
#
# ## global config ##
["mypy.ini".mypy]
warn_return_any = true
warn_unused_configs = true
warn_unreachable = true
strict_optional = true

disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
show_none_errors = true

warn_no_return = true

warn_redundant_casts = true
warn_unused_ignores = true

pretty = true

# ## test code config ##
["mypy.ini"."mypy-tests.*"]
ignore_missing_imports = true
warn_return_any = false
warn_unreachable = false
strict_optional = false
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = false
show_none_errors = false
warn_no_return = false
warn_unused_ignores = false

#
# pipenv config
#
["Pipfile".dev-packages]
black = "*"
flake8 = "*"
flake8-docstrings = "*"
isort = "*"
mypy = "*"
nitpick = "*"
pytest = "*"
pytest-cov = "*"

["Pipfile".scripts]
nitpick-check = "nitpick check"
nitpick-fix = "nitpick fix"
lint = "flake8 --show-source ."
mypy = "mypy ."
test = "pytest --junitxml=test-results.xml --cov=. --cov-report=xml"
