[nitpick]
minimum_version = "0.32.0"

[nitpick.styles]
include = [
  "nitpick-python-styles.toml",

  "styles/aws-lambda-py310-style.toml",
  "styles/aws-sam-style.toml",
  "styles/moto-pytest-style.toml",
  "styles/cfn-lint-style.toml"
]