[nitpick]
minimum_version = "0.32.0"

[nitpick.styles]
include = [
  "styles/pytest-style.toml",
  "styles/vscode-style.toml",
  "styles/black-isort-style.toml",
  "styles/flake8-style.toml",
  "styles/mypy-style.toml",
]