[nitpick.styles]
include = [
  "nitpick-style.toml"
]

#
# mypy config
#
# ## ignore no imports for `moto` stubs ##
["mypy.ini".mypy-moto]
ignore_missing_imports = true

#
# pytest-env config
#
["pyproject.toml".tool.pytest.ini_options]
# to prevent tests mutate the real aws environments.
# http://docs.getmoto.org/en/latest/docs/getting_started.html?highlight=default_region#how-do-i-avoid-tests-from-mutating-my-real-infrastructure
env = [
  "AWS_ACCESS_KEY_ID=testing",
  "AWS_SECRET_ACCESS_KEY=testing",
  "AWS_SECURITY_TOKEN=testing",
  "AWS_SESSION_TOKEN=testing",
  "AWS_DEFAULT_REGION=ap-northeast-1",
  "LOG_LEVEL=DEBUG",
]

["Pipfile".dev-packages]
# each projects should depend boto3/moto with specific "extras" 
#boto3 = "*"
#boto3-stubs = {extras = ["essential"], version = "*"}
#moto = "*"

# if you want install aws cli and sam cli in venv through pipenv,
# uncomment below lines.
# aws-cli = "*"
# sam-cli = "*"

pytest-env = "*"
cfn-lint = "*"

["Pipfile".requires]
# current latest runtime version aws lambda
python_version = "3.9"

["Pipfile".scripts]
cfn-lint = "cfn-lint template.yaml"