[nitpick.styles]
include = [
  "pytest-style.toml"
]

#
# pytest-env config
#
["pyproject.toml".tool.pytest.ini_options]
# to prevent tests mutate the real aws environments.
# http://docs.getmoto.org/en/latest/docs/getting_started.html?highlight=default_region#how-do-i-avoid-tests-from-mutating-my-real-infrastructure
env = [
  "AWS_ACCESS_KEY_ID=testing",
  "AWS_SECRET_ACCESS_KEY=testing",
  "AWS_SECURITY_TOKEN=testing",
  "AWS_SESSION_TOKEN=testing",
  "AWS_DEFAULT_REGION=ap-northeast-1",
]

#
# mypy config
#
# ## ignore no imports for `moto` stubs ##
["mypy.ini".mypy-moto]
ignore_missing_imports = true

["Pipfile".dev-packages]
moto = {version = "*"}
pytest-env = "*"

